version : '3.9'
services:
  ununtu:
    build:
      context: .
      dockerfile: ./dockerfiles/ubuntu/Dockerfile
    container_name: project_build
    hostname: project_build
    volumes:
      - webapps:/usr/local/tomcat/webapps:rw

  tomcat:
    build:
      image: tomcat:10.0-jdk11-temurin-focal
    container_name: project_tomcat
    hostname: project_tomcat
    volumes:
      - webapps:/usr/local/tomcat/webapps:rw
    networks:
      - project_net
<<<<<<< HEAD
    ports: '8080:8080'
  
=======
    depends_on:
      - ubuntu
    ports: 8080:8080   
>>>>>>> bb5fe99f79beb37b68e659e8dc6108f6c4bac32f

volumes:
  webapps:
networks:
  project_net: